query Category($id: ID!) {
  category(id: $id) {
    gifts(sort: "name:asc") {
      id
      name
      price
      categories {
        name
      }
      brand {
        name
      }
      image {
        url
      }
    }
  }
}
