query Gift($id: ID!) {
  gift(id: $id) {
    id
    name
    description
    price
    categories {
      name
    }
    brand {
      name
      description
      logo {
        url
      }
    }
    image {
      url
    }
  }
}
