query Order($id: ID!) {
  order(id: $id) {
    id
    gift {
      name
      brand {
        name
      }
      image {
        url
      }
    }
    background {
      image {
        url
      }
    }
    message
    quantity
  }
}
